// <auto-generated />
namespace CovidHealthcareApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_hospital_add_doctor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_hospital_add_doctor));
        
        string IMigrationMetadata.Id
        {
            get { return "202107191906260_update_hospital_add_doctor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
